### ISSUE TITLE
Korean Translation for column / row

### ISSUE THREAD

**Issue by daewonyoon** [typora/Typora-i18n#130]
currently
```
"Columns" = "열";
"Rows" = "행";
--
"Add Row Above" = "앞에 행 삽입";
"Add Row Below" = "뒤에 행 삽입";
"Delete Row" = "행 삭제";
"Add Column Before" = "앞에 열 삽입";
"Add Column After" = "뒤에 열 삽입";
"Delete Column" = "열 삭제";

```

should be
```
"Columns" = "행";
"Rows" = "열";
--
"Add Row Above" = "앞에 열 삽입";
"Add Row Below" = "뒤에 열 삽입";
"Delete Row" = "열 삭제";
"Add Column Before" = "앞에 행 삽입";
"Add Column After" = "뒤에 행 삽입";
"Delete Column" = "행 삭제";
```

**Comment by ksundong** [comment]
해당항목 확인을 해보았으나 정상적으로 보이는 것 같습니다.

참조: http://egloos.zum.com/hhugs/v/3762318
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://kenarie.tistory.com/114
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://boardlife.co.kr/bbs_detail.php?bbs_num=7511&tb=community_qna&id=google_117463440659009851831&num=&pg=&game_id=&start=&b_category=&game_category=

**Comment by daewonyoon** [comment]
앗. 죄송합니다. `row = 열` 이라고 생각하고 착각했네요.

**Comment by ksundong** [comment]
Typora에서 자체적으로 표기하는게 잘못되어있지 않나 싶네요.
지금 확인해보니까 반대로 나오는게 맞는 것 같습니다.
Translate의 문제는 아닌 것 같고, Typora에 직접 문의 해봐야겠습니다.
