### ISSUE TITLE
Smart Quotes - a bit different for some languages

### ISSUE THREAD

**Issue by Vegebutcher** [typora/Typora-i18n#135]
Smart Quotes is a superb feature, but it should take into account the fact that in some languages, e.g. in Polish, the opening quote character is slightly different: `„` (U+201E) instead of `“` (U+201C).

**Comment by abnerlee** [comment]
They are configurable.

On Windows/Linux version, you could find more quote pair patterns in Preferences Panel, like “«abc» “, etc.

On macOS version, you could set quote patterns in System Preferences → Keyboard → Text. If it is changed, Typora will need a restart to apply it.

**Comment by Vegebutcher** [comment]
Thanks for the tip! I haven't noticed the drop-down list :D
