### ISSUE TITLE
Italian translation [it-IT]

### ISSUE THREAD

**Issue by starise** [typora/Typora-i18n#14]
I'll start working on the italian translation this weekend. =)
Cya soon! 👍

**Comment by Schokobecher** [comment]
Hey @starise, did you translate `Menu.strings` by hand? I'm having a hard time following up with localize-mainmenu since no .xliff are provided for the languages

**Comment by starise** [comment]
@Schokobecher yes, unfortunately I'm translating all the files by hand.

**Comment by Schokobecher** [comment]
Translating the menu file by hand is kinda standing against what localize-mainmenu is designed to do. Maybe the docs/repo need an overhaul.

But I guess I'm going for the manual route then.

**Comment by abnerlee** [comment]
Unfortunately, someone already submitted his Italian translation, you may refer to his https://github.com/typora/Typora-i18n/pull/17 to check if there are any mistranslations.

**Comment by starise** [comment]
Yes, at a first sight there are various mistakes. Translations are not "word by word" but interpreting expressions that are coherent in your language and consistent with similar software.

Pardon me @abnerlee, but I've realized many translations and I know what I say.

I want to remember you the first rule (shouldn't it be the first thing to do before starting a work?) in your "[README.md](https://github.com/typora/Typora-i18n/blob/master/Readme.md)" file:

> 2. **Check our issue list to see if there are already someone else translating the text recourse to your language**. If not, open an issue to tell others that you doing the translation, in order to avoid duplicate work.

So you're saying that someone that isn't able to read that simple first rule, has submitted his translations and I wasted my time doing my job for free the most precise and professional possible. He didn't even followed the "folder name" structure as the others. Of course, rule 3

> 3. Create a folder named {locale}.lproj, local code should be picked from locale-identifiers.csv.

95% of my translation is done and a pull request was on its way. Now, should I have to throw away my work and (re-)check and make corrections of someone else work that started without reading a couple of simple rules? 

Well, honestly I don't know what to say.

**Comment by abnerlee** [comment]
Sorry, I should ask about your progress first since if you just start, then we can use the existing one and modified based on his translation, so you won't wasted your time.

I do not speak italian so I do not know the quality of his translation. But we do have simple rules for translation, and I would consider those who read our readme more "professional". 

If you have done most of the translation, then feel free to make a pull request, we would prefer yours since you did it first, and read our simple rules.

**Comment by starise** [comment]
Ok, don't worry, it was just an (evitable) waste of resources. I'm very busy and I'd have liked if the other translator said "hi" in this 'thread' to help. Anyway i make the last revision then I'll send the pull request.

**Comment by abnerlee** [comment]
Merged
