### ISSUE TITLE
Translation mistake in de-DE.lproj/Panel.strings

### ISSUE THREAD

**Issue by skozitzki** [typora/Typora-i18n#167]
I found a translation mistake in the german translation:
https://github.com/typora/Typora-i18n/blob/0976678b1d7a1ebead080f2362556cb78c6435f7/de-DE.lproj/Panel.strings#L300

The correct translation is as follows:
`"Quit and Install" = "Beenden und installieren";`

**Comment by abnerlee** [comment]
Fixed in https://github.com/typora/Typora-i18n/commit/9f1cb5faab13b92785b72e0558e63c2f88773181

will be applied to Typora in future version ups.
