### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by ahmedelq** [typora/Typora-i18n#176]
Currently working on the Arabic translation.

**Comment by alaaio** [comment]
I would like to help on the Arabic translation. Please contact me.

**Comment by ahmedelq** [comment]
Thank you for joining Aalaa, please fork https://github.com/ahmedelq/Typora-i18n
Almost finished, but there's always a room for improvement.

**Comment by abnerlee** [comment]
Done in #179
