### ISSUE TITLE
MacOS Big Sur bug with keyboard shortcuts 

### ISSUE THREAD

**Issue by L-Clem** [typora/Typora-i18n#184]
Hi, 
I have a problem on macOS Big Sur, the keyboard shortcuts for titles aren't working. I can just hear a "bump" sound.
Thanks for your hard work.

**Comment by abnerlee** [comment]
You mean `command+1`? in my test it is still working on Big Sur.

**Comment by L-Clem** [comment]
Sorry for being this late (I forgot about me opening this issue...). I will check this soon and let you know.

**Comment by L-Clem** [comment]
Sorry for being this late. The problem solved itself. Thanks for all.
