### ISSUE TITLE
String error "Repalce" = "Replace" and other typos;

### ISSUE THREAD

**Issue by starise** [typora/Typora-i18n#19]
It looks like there's an [error in the "_Base.lproj_" file on the line 25](https://github.com/typora/Typora-i18n/blob/master/Base.lproj/Front.strings#L25).

"Repalce" should be "Replace", right?

**Comment by starise** [comment]
Found other typos here and there. Hope i caught them all.

**Comment by abnerlee** [comment]
merged in https://github.com/typora/Typora-i18n/pull/21
