### ISSUE TITLE
Missing "Total" string in Panel.strings

### ISSUE THREAD

**Issue by starise** [typora/Typora-i18n#22]
I noticed a missing word into the "[Base > Panel.strings](https://github.com/typora/Typora-i18n/blob/master/Base.lproj/Panel.strings)" file into the "Word Count" section. Yet it's present into the "[zh-Hans > Panel.strings](https://github.com/typora/Typora-i18n/blob/2f8543b9e0635589a22eec304b5aaab783374cb3/zh-Hans.lproj/Panel.strings#L129)" translation.

It should be referred to the "Total" word from the image below.

![Total word](https://s18.postimg.org/akt177rop/typora-total.png)

**Comment by starise** [comment]
About the same topic, looking at the translation applied into the version "0.6.42" (I use the Win version of Typora) i see that the string used on the top that should be "Total", takes the translation from "[Word Count](https://github.com/typora/Typora-i18n/blob/904eaa647ea5ef7c62585869b27a1c207c18cc64/it-IT.lproj/Panel.strings#L20)" string into "Panel.strings".

![image](https://user-images.githubusercontent.com/2684482/35383245-00550cf0-01c2-11e8-8d60-155a125de893.png)

But this it is actually untrue, because the menu shows minutes, rows and characters count, not just "words" (in italian "parole"). The above should be translated as "Total".

Anyway I noticed that this happens only when no text is selected into the document. Selecting a word or a phrase, "In selection" ("selezionati" in italian) appears and the string changes in "Total", this is probably an issue from of Typora not just the translation, anyway I thought to put it here.

![image](https://user-images.githubusercontent.com/2684482/35383454-a751acca-01c2-11e8-866f-393d0c6314fc.png)

**Comment by abnerlee** [comment]
When no text is selected the header shows "word count".
When something is selected, the header shows "total" and the bottom area shows "in selection", so user can distinguish those two parts.

**Comment by abnerlee** [comment]
Also added in https://github.com/typora/Typora-i18n/commit/04218fa423fc29054c5dea5a24b8b9e3a82266fb
