### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by sponka9** [typora/Typora-i18n#232]
Hello, I'v been using Typora for some time and to my surprise slovenian translation (sl-si) does not exist, yet.
Everything translated except Panel.strings -- need day or two to finish (not enough spare time :)
And since it's my first github project, must figure out how to publish everytning ...

**Comment by abnerlee** [comment]
Thanks.

> And since it's my first github project, must figure out how to publish everytning

You can google "github pull request", that may help
