### ISSUE TITLE
ja_JP support for Welcome.strings

### ISSUE THREAD

**Issue by Yukinosuke-Takada** [typora/Typora-i18n#285]
I've noticed that Welcome.strings in ja_JP wasn't translated. I have started to translate it:)

**Comment by Hayao0819** [comment]
What happened to this work afterwards?

I am trying to do a translation, but if you have one already completed please create a PR.

**Comment by Yukinosuke-Takada** [comment]
https://github.com/typora/Typora-i18n/pull/286 
This is the PR

**Comment by Yukinosuke-Takada** [comment]
#286

**Comment by Hayao0819** [comment]
Thanks.
