### ISSUE TITLE
[zh-Hans/zh-CN] Typo on status bar's button hover text

### ISSUE THREAD

**Issue by sdygt** [typora/Typora-i18n#29]
Typora 0.9.41
The translation of "Toggle Sidebar" button's hover text should be “显示/隐藏侧边栏” (literally "Show/Hide sidebar") , not “现实/隐藏侧边栏”.
![default](https://user-images.githubusercontent.com/11964392/35290315-d7757f86-00a4-11e8-9388-f6ac1d9fd87e.png)

I guess https://github.com/typora/Typora-i18n/blob/master/zh-Hans.lproj/Front.strings#L86 is related. However the translation here is correct 🤣🤣

**Comment by abnerlee** [comment]
This is fixed in one merge request. The new translation will be applied in next version up.
