### ISSUE TITLE
Missing Strings or not translated strings

### ISSUE THREAD

**Issue by starise** [typora/Typora-i18n#32]
I think this could be a place to put all the missing strings or not translated strings from Typora. This should be useful for all, author and translator to locate them.

**Comment by starise** [comment]
I found that the search ("ctrl+f" on Windows) the submenu "Replace" is not translated correctly as you can see below. There are also 2 missing strings, "focus" dropdown descriptions "Case Sensitive" and "Whole Word" from the related buttons.
![image](https://user-images.githubusercontent.com/2684482/35384853-e1205f74-01c6-11e8-9b69-ef14fbe6558d.png)

**Comment by abnerlee** [comment]
Added in https://github.com/typora/Typora-i18n/commit/04218fa423fc29054c5dea5a24b8b9e3a82266fb

"Replace" is fixed in https://github.com/typora/Typora-i18n/commit/645b8b6ae658329dbb670cfc654d37eeb6e51d25

**Comment by starise** [comment]
"search text" was already existing as string, and is duplicated in Front.strings:

[L28](https://github.com/typora/Typora-i18n/blob/04218fa423fc29054c5dea5a24b8b9e3a82266fb/Base.lproj/Front.strings#L28) => [L128](https://github.com/typora/Typora-i18n/blob/04218fa423fc29054c5dea5a24b8b9e3a82266fb/Base.lproj/Front.strings#L128)
