### ISSUE TITLE
Missing string resource for 'Export Setting...' menu item in 'File\Export' menu

### ISSUE THREAD

**Issue by BrainCrumbz** [typora/Typora-i18n#337]
Hello all

as per title, we were trying to improve Italian translation, but we could not find where in this repository is the string resource for this bit of UI:

![immagine](https://user-images.githubusercontent.com/3185573/175340126-073fc6d3-d030-49b0-864b-8efba3fcd8b5.png)

**Comment by abnerlee** [comment]
in https://github.com/typora/Typora-i18n/blob/master/Base.lproj/Menu.strings#L322

All labels in menu or context menu should be located in the Menu.strings file
