### ISSUE TITLE
Missing string resource for 'Hyperlink Actions' menu item in 'Format' menu

### ISSUE THREAD

**Issue by BrainCrumbz** [typora/Typora-i18n#338]
Hello all

as per title, we were trying to improve Italian translation, but we could not find where in this repository is the string resource for this bit of UI:

![immagine](https://user-images.githubusercontent.com/3185573/175344702-4487823a-6ba5-4a41-ac58-8c28c6bbece6.png)

**Comment by abnerlee** [comment]
in https://github.com/typora/Typora-i18n/blob/master/Base.lproj/Menu.strings#L317

All labels in menu or context menu should be located in the Menu.strings file

**Comment by BrainCrumbz** [comment]
Oh I see, thanks, did not figured out this. We were looking in the language-specific Menu.strings file and could not find it.  
Got it.
