### ISSUE TITLE
Translation not applied for 'HTML (without styles)' menu item in 'File\Export' menu

### ISSUE THREAD

**Issue by BrainCrumbz** [typora/Typora-i18n#340]
Hello all

while trying to improve Italian translation, we noticed that mentioned menu item *\*is\** actually translated in [Menu string resources](https://github.com/typora/Typora-i18n/blob/3d7d3382dce3e3e1e7a2d268f0e73dda1162631a/it-IT.lproj/Menu.strings#L292), but for some reason the menu item still shows up un-translated in UI:

![immagine](https://user-images.githubusercontent.com/3185573/175349042-40096258-ee35-42e8-8a2e-6f82863f53bd.png)

**Comment by abnerlee** [comment]
It is now defined in Preferences Panel → Export, user can edit and rename it. So it is not available for translations

**Comment by BrainCrumbz** [comment]
Hi. Thanks for info.  
We're on v.1.3.7 and not all items in Preferences\Export are editable. That one in particular seems not editable:

![immagine](https://user-images.githubusercontent.com/3185573/175494742-3b910bd6-2caa-46fc-99c6-c0a4026d0b7f.png)

Not an issue, just mentioning it for completeness.
