### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by byDave251** [typora/Typora-i18n#35]
I am translating Typora to Czech. It'll be early! / Překládám Typoru do češtiny. Bude to brzy!

**Comment by psimacek** [comment]
Ech, taky jsem začal. Tak už jsem to zase ukončil :-)

**Comment by byDave251** [comment]
😂😂 Nevadí. Ještě než jste začal jste si měl zkontrolovat issue, jestli na tom už někdo nepracuje jak je psáno v README.

**Comment by abnerlee** [comment]
close by https://github.com/typora/Typora-i18n/pull/38
