### ISSUE TITLE
Visualize the state of translation

### ISSUE THREAD

**Issue by Hayao0819** [typora/Typora-i18n#382]
Currently, the translation status is not visualized.

This means that translators need to manually find and translate untranslated portions.

I am writing a small script to automate this tedious and cumbersome task.

If anyone needs it I will tidy it up and add it to the project, but I would like to hear from others.

**Comment by Hayao0819** [comment]
Current progress is here.

This compares each lang with the base and shows the percentage of the translation that has been completed.

<img width="446" alt="image" src="https://github.com/typora/Typora-i18n/assets/32128205/af354107-2c0e-4ef8-999b-6c7de9e2f155">

**Comment by Hayao0819** [comment]
And it is a list of missing keys in Japanese.

<img width="1198" alt="image" src="https://github.com/typora/Typora-i18n/assets/32128205/17193d18-5a7e-491f-a2a8-fb7a6cbaa97b">

**Comment by Hayao0819** [comment]
Key list diff

<img width="1123" alt="image" src="https://github.com/typora/Typora-i18n/assets/32128205/12014208-3303-40fe-8f37-979a0048123a">

**Comment by abnerlee** [comment]
I updated Readme.md about this tools, you can also make PR to modify README directly if anything is missing or you want to put more details there.

**Comment by Hayao0819** [comment]
I hope this tool will help other translators.Something for the tool.Something buggy in the tool.If you find any bugs in the toolIf you find any bugs in the tool, please contact us atIf you find any bugs in the tool, please let me know!

**Comment by Hayao0819** [comment]
I hope this tool will help other translators. Please let me know if you find any bugs in any of the tools.
