### ISSUE TITLE
Croatian not listed?

### ISSUE THREAD

**Issue by diomed** [typora/Typora-i18n#70]
When I go under Preferences I don't see Croatian in the dropdown list of languages

**Comment by abnerlee** [comment]
You cannot find "Hrvatski"?

What's you Typora version?

**Comment by diomed** [comment]
![screenshot_4](https://user-images.githubusercontent.com/72777/39665584-17813c5e-5097-11e8-81c7-9557f93fca16.png)
My Typora version is 0.9.50

**Comment by abnerlee** [comment]
Yes, Seems missed on Windows/Linux version, we will add that in next release

**Comment by abnerlee** [comment]
listed in 0.9.51
