### ISSUE TITLE
Check updates string doesn't translate [bug]

### ISSUE THREAD

**Issue by diomed** [typora/Typora-i18n#78]
https://github.com/typora/Typora-i18n/blob/893a2d782050874d2f32906d0d85c64514ad4ce5/Base.lproj/Menu.strings#L12

yeah, I checked several languages, and this string doesn't translate at all, despite our translations.
something's off.

**Comment by DHclly** [comment]
> [Typora-i18n/Base.lproj/Menu.strings](https://github.com/typora/Typora-i18n/blob/893a2d782050874d2f32906d0d85c64514ad4ce5/Base.lproj/Menu.strings#L12)
> 
> Line 12 in [893a2d7](/typora/Typora-i18n/commit/893a2d782050874d2f32906d0d85c64514ad4ce5)
> 
>  "Check for Updates" = "Check for Updates"; 
> yeah, I checked several languages, and this string doesn't translate at all, despite our translations.
> something's off.

why not make a pull request ?
