### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dtypeanalytics** [typora/Typora-i18n#85]
I tweeted this to you guys earlier..

Feature Request:  Add a global setting for a default programming language for 'code fences'.

In a typical document, I can have as many as 10 to 15 code blocks and all of them are the same programming language.  It would save a lot of time just to set a default language for all code blocks instead of typing it in for each one.

Thanks very much
John

**Comment by diomed** [comment]
this is wrong repo - this repo is for translation questions only. 

you need to post in: https://github.com/typora/typora-issues
and  close this issue, since it's not related to actual language translation
