### ISSUE TITLE
Need translation of Markdown Reference.md?

### ISSUE THREAD

**Issue by ljylin** [typora/Typora-i18n#90]
There seems to be no translation of the documentation in the repository. I translated `Markdown Reference.md` into Chinese. Do you need it?

**Comment by abnerlee** [comment]
Sure, thanks a lot.

If it is available online, you could just add a link in <https://github.com/typora/wiki-website/blob/gh-pages/_posts/2016-01-01-Markdown%20Reference.md>

Or, make a "zh-Hans" subfolder in <https://github.com/typora/wiki-website/blob/gh-pages/> and put your translation there.
